services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        WP_VERSION: ${WP_VERSION}
        WSL_USER: ${WSL_USER}
        WSL_USER_ID: ${WSL_USER_ID}

    image: wordpress:${WP_VERSION}-php${PHP_VERSION}-apache

    volumes:
      - ./:/var/www/html
    
    command: >
      bash -c "
        mkdir -p /var/www/html/wp-content/upgrade &&
        chown -R ${WSL_USER}:www-data /var/www/html &&
        find /var/www/html -type d -exec chmod 2775 {} \\; &&
        find /var/www/html -type f -exec chmod 644 {} \\; &&
        su -s /bin/bash ${WSL_USER} -c 'composer install --no-interaction' &&
        exec docker-entrypoint.sh apache2-foreground
      "

    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_SITEURL: ${WP_SITEURL}

    ports:
      - "${APACHE_PORT}:80"

    networks:
      - public-services

networks:
  public-services:
    external: true